title: ESOUI Code Collection
description: Collection of Elder Scrolls Mods
exclude: [
  '_pagebuilder/',
  '.idea/**',
]
theme: jekyll-theme-cayman
gems:
  - jekyll-mentions
plugins:
  - jekyll-relative-links
