title: Yu-Gi-Oh! Duel Links Fansite
description: Collection of Yu-Gi-Oh! Duel Links Information
exclude: [
  '_pagebuilder/',
  '.idea/**',
]
theme: jekyll-theme-cayman
gems:
  - jekyll-mentions
plugins:
  - jekyll-relative-links
